<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE Books [
    <!ELEMENT Books  (bookrecord+)>
    <!ELEMENT bookrecord (title,author+,year,price,category)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT category (#PCDATA)>

]>

<Books>
    <bookrecord>
      <title>Everyday Italian</title>
      <author>Giada De Laurentiis</author>
      <year>2005</year>
      <price>30</price>
      <category>cooking</category>
    </bookrecord>
    <bookrecord>
      <title>Harry Potter</title>
      <author>J K. Rowling</author>
      <year>2005</year>
      <price>29.99</price>
      <category>children</category>
    </bookrecord>
    <bookrecord>
      <title>XQuery Kick Start</title>
      <author>James McGovern</author>
      <author>Per Bothner</author>
      <author>Kurt Cagle</author>
      <author>James Linn</author>
      <author>Vaidyanathan Nagarajan</author>
      <year>2003</year>
      <price>49.99</price>
      <category>web</category>
    </bookrecord>
    <bookrecord>
      <title>Learning XML</title>
      <author>Erik T. Ray</author>
      <year>2005</year>
      <price>39.95</price>
      <category>web</category>
    </bookrecord>
  </Books>
